name: release
on: push

#on:
#  release:
#    types:
#      - created

jobs:
  gcs-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: release gcs
        env:
          GCS_CREDS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo ${GCS_CREDS} >> .creds.json
          docker run --rm \
          -e CGO_ENABLED=0 \
          -e GO111MODULE=on \
          -e GOOGLE_APPLICATION_CREDENTIALS=/build/src/.creds.json \
          --volume=${PWD}:/build/src \
          --workdir=/build/src/cmd \
          golang@sha256:5219b39d2d6bf723fb0221633a0ff831b0f89a94beb5a8003c7ff18003f48ead \
          go run .